### ISSUE TITLE
Manifest parse error with Xcode 11.4

### ISSUE THREAD

**Issue by dsalber** [mongodb/swift-mongoc#2]
To reproduce:

- in Xcode 11.4, create a new macOS app project
- go to File > Swift Packages > Add Package Dependency
- add https://github.com/mongodb/swift-mongoc.git

Result: 

Error "Package Resolution Failed", "manifest parse error: target 'mongoc' referenced in product 'mongoc' could not be found", see screenshot.

<img width="726" alt="Screen Shot 2020-03-30 at 17 32 44" src="https://user-images.githubusercontent.com/308751/77931494-86d0e580-72ac-11ea-9a11-adf4a7349e08.png">

(Note: I have mongo-c-driver-1.16.2.catalina installed through homebrew.)

**Comment by Rep2** [comment]
Having the same issue. Is anyone maintaining the repo?

**Comment by kmahar** [comment]
Hi @dsalber, thank you for reaching out and sorry I didn't see this issue sooner.
It seems that the way in which we've set up in the bindings in this repo are no longer compatible with Swift 5.2.
Are you encountering this via trying to use mongo-swift-driver, or are you trying to use libmongoc directly from a Swift application?

**Comment by dsalber** [comment]
Hi @kmahar, I ran into this while trying to use mongo-swift-driver indeed.

**Comment by kmahar** [comment]
@dsalber thanks for the info! This is the same issue being discussed in mongodb/mongo-swift-driver#448 now so if you don't mind I'd like to close this issue and condense the conversation to that thread.
I suggested one possible solution there (use the newer version of the driver, which no longer depends on `swift-mongoc`) but please feel free to chime in there with more info there about your use case and hopefully we can work out a solution for you.
